encuesta/urls.py
from django.urls import path


from . import views


app_name = 'encuesta'


urlpatterns = [
    path('', views.index,name='index'),
    path('<int:pregunta_id>/',views.detalle,name='detalle'),
    path('<int:pregunta_id>/votar',views.votar,name='votar')
]

lab3/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('encuesta/',include('encuesta.urls')),
    path('tarea/',include('tarea.urls')),
]

tarea/urls.py
from django.urls import path
from . import views

app_name = 'tarea'

urlpatterns = [
    path('', views.index,name='index'),
    path('clientes/', views.clientes,name='clientes'),
    path('client/<int:cliente_id>/',views.cliente,name='cliente'),
    path('productos/',views.productos,name='productos'),
    path('producto/<int:producto_id>/',views.producto,name='producto'),
    path('proveedores/',views.proveedor,name='proveedores'),
    path('ventas/',views.ventas,name='ventas'),
]

encuesta/models.py
from django.db import models

class Pregunta(models.Model):
    pregunta_texto = models.CharField(max_length=200)
    pub_date = models.DateField('date published')


class Opcion(models.Model):
    pregunta = models.ForeignKey(Pregunta, on_delete=models.CASCADE)
    opcion_texto = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)

tarea/models.py
from django.db import models

class Direccion(models.Model):
    calle = models.CharField(max_length=100)
    numero = models.CharField(max_length=10)
    comuna = models.CharField(max_length=50)
    ciudad = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.calle}, {self.numero}, {self.comuna}, {self.ciudad}"

class Proveedor(models.Model):
    codigo = models.CharField(max_length=10, unique=True)
    nombre = models.CharField(max_length=100)
    direccion = models.ForeignKey(Direccion, on_delete=models.CASCADE)
    telefono = models.CharField(max_length=20)
    pagina_web = models.URLField()

    def __str__(self):
        return self.nombre

class Categoria(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    identificador = models.CharField(max_length=10, unique=True)
    nombre = models.CharField(max_length=100)
    precio_actual = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

class Cliente(models.Model):
    codigo = models.CharField(max_length=10, unique=True)
    nombre = models.CharField(max_length=100)
    direccion = models.ForeignKey(Direccion, on_delete=models.CASCADE)
    telefonos = models.ManyToManyField('Telefono')

    def __str__(self):
        return self.nombre

class Telefono(models.Model):
    numero = models.CharField(max_length=20)

    def __str__(self):
        return self.numero

class Venta(models.Model):
    numero_factura = models.CharField(max_length=20, unique=True)
    fecha = models.DateField()
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    descuento = models.DecimalField(max_digits=5, decimal_places=2)
    monto_final = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.numero_factura

class VentaProducto(models.Model):
    venta = models.ForeignKey(Venta, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    precio_venta = models.DecimalField(max_digits=10, decimal_places=2)
    cantidad_vendida = models.PositiveIntegerField()
    monto_total = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.venta.numero_factura} - {self.producto.nombre}"

encuesta/views.py
from django.shortcuts import render
from .models import Opcion,Pregunta

# Create your views here.
def index(request):
    latest_question_list = Pregunta.objects.order_by('-pub_date')[:5]
    context = {
        'latest_question_list':latest_question_list
    }
    return render(request,'encuesta/index.html',context)


def detalle(request,pregunta_id):
    pregunta = Pregunta.objects.get(pk=pregunta_id)
    context = {
        'pregunta':pregunta
    }
    
    return render(request,'encuesta/detalle.html',context)


def votar(request,pregunta_id):
    pregunta = Pregunta.objects.get(pk=pregunta_id)
    opcionSeleccionada = pregunta.opcion_set.get(pk=request.POST['opcion'])
    opcionSeleccionada.votos += 1
    opcionSeleccionada.save()
    context = {
        'pregunta':pregunta
    }
    return render(request,'encuesta/resultados.html',context)

tarea/views.py
from django.shortcuts import render
from .models import *

def index(request):
    return render(request,'tarea/index.html')

def clientes(request):
    clientes = Cliente.objects.all()
    return render(request,'client/clientes.html',{"clientes":clientes})

def cliente(request,cliente_id):
    cliente = Cliente.objects.get(pk=cliente_id)
    telefonos = cliente.telefonos.all()
    return render(request,'client/client.html',{"cliente":cliente,"telefonos":telefonos})

def proveedor(request):
    proveedores = Proveedor.objects.all()
    return render(request, 'proveedor/proveedores.html',{"proveedores":proveedores})


def productos(request):
    productos = Producto.objects.all()
    return render(request,'producto/productos.html',{'productos':productos})

def producto(request, producto_id):
    producto = Producto.objects.get(id=producto_id)
    return render(request, 'producto/producto.html',{'producto':producto})

def ventas(request):
    ventas = VentaProducto.objects.all()
    return render(request,'ventas/ventas.html',{'ventas':ventas})

encuesta/templates/encuesta/detalle.html
<h1>{{ pregunta.pregunta_texto }}</h1>

<form action="{% url 'encuesta:votar' pregunta.id %}" method="post">
    {% csrf_token %}
    {% for opcion in pregunta.opcion_set.all %}
        <input type="radio" name="opcion" id="opcion{{ forloop.counter }}" value="{{ opcion.id}}">
        <label for="opcion{{forloop.counter }}">{{ opcion.opcion_texto }}</label><br>
    {% endfor %}
    <input type="submit" value="votar">
</form>
<a href="{% url 'encuesta:index' %}">Ver Preguntas</a>

encuesta/templates/encuesta/index.html
<h1>Encuesta</h1>
{% if latest_question_list %}
    <ul>
        {% for pregunta in latest_question_list %}
            <li>
                <a href="/encuesta/{{pregunta.id}}">
                    {{pregunta.pregunta_texto}}
                </a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No hay registros</p>
{% endif %}

encuesta/templates/encuesta/resultados.html
<h1>{{ pregunta.pregunta_texto }}</h1>
<ul>
    {%for opcion in pregunta.opcion_set.all %}
        <li>{{opcion.opcion_texto }} -- {{opcion.votos }} voto{{ opcion.votos|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'encuesta:detalle' pregunta.id %}">Votar de nuevo</a>
<a href="{% url 'encuesta:index' %}">Ver Preguntas</a>

tarea/templates/client/client.html
<p>Codigo: {{cliente.codigo}}</p>
<p>Nombre: {{cliente.nombre}}</p>
<p>Direccion: {{cliente.direccion}}</p>
{% for t in telefonos %}
<p>Telefono: {{t}}</p>
{% endfor %}

tarea/templates/client/clientes.html
{% for c in clientes %}
<ul>
    <li><a href="{% url 'tarea:cliente' c.id %}">{{c}}</a></li>
</ul>
{% endfor %}

tarea/templates/producto/producto.html
<p>Identificador: {{producto.identificador}}</p>
<p>Nombre: {{producto.nombre}}</p>
<p>Precio actual: {{producto.precio_actual}}</p>
<p>Stock: {{producto.stock}}</p>
<p>Proveedor: {{producto.proveedor}}</p>
<p>Categoria: {{producto.categoria}}</p>
<p>Categoria-Descripcion: {{producto.categoria.descripcion}}</p>

tarea/templates/producto/productos.html
{% for p in productos %}
<ul>
    <li><a href="{% url 'tarea:producto' p.id %}">{{p}}</a></li>
</ul>
{% endfor %}

tarea/templates/proveedor/proveedores.html
<table border="1">
    <thead>
        <tr>
            <th>Codigo</th>
            <th>Nombre</th>
            <th>Direccion</th>
            <th>Telefono</th>
            <th>Pagina web</th>
        </tr>
    </thead>
    <tbody>
        {% for pro in proveedores %}
        <tr>
            <td>{{ pro.codigo }}</td>
            <td>{{ pro.nombre }}</td>
            <td>{{ pro.direccion }}</td>
            <td>{{ pro.telefono }}</td>
            <td>{{ pro.pagina_web }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

tarea/templates/tarea/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tarea</title>
</head>
<body>
    <a href="{% url 'tarea:clientes' %}">Clientes</a>
    <a href="{% url 'tarea:productos' %}">Productos</a>
    <a href="{% url 'tarea:proveedores' %}">Proveedor</a>
    <a href="{% url 'tarea:ventas' %}">Ventas</a>
</body>
</html>

tarea/templates/ventas/ventas.html
<table border="1">
    <thead>
        <tr>
            <th>Número de Factura</th>
            <th>Fecha</th>
            <th>Cliente</th>
            <th>Descuento</th>
            <th>Monto Final</th>
            <th>Producto</th>
            <th>Precio de Venta</th>
            <th>Cantidad Vendida</th>
            <th>Monto Total</th>
        </tr>
    </thead>
    <tbody>
        {% for venta in ventas %}
        <tr>
            <td>{{ venta.venta.numero_factura }}</td>
            <td>{{ venta.venta.fecha }}</td>
            <td>{{ venta.venta.cliente.nombre }}</td>
            <td>{{ venta.venta.descuento }}</td>
            <td>{{ venta.venta.monto_final }}</td>
            <td>{{ venta.producto.nombre }}</td>
            <td>{{ venta.precio_venta }}</td>
            <td>{{ venta.cantidad_vendida }}</td>
            <td>{{ venta.monto_total }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>